CREATE TABLE med_supp (
  id SERIAL PRIMARY KEY,
  company VARCHAR NOT NULL,
  company_old VARCHAR NOT NULL,
  naic VARCHAR NOT NULL,
  plan VARCHAR NOT NULL,
  state VARCHAR NOT NULL,
  area VARCHAR NOT NULL,
  zip_lookup_code VARCHAR NOT NULL,
  gender VARCHAR NOT NULL,
  t_nt VARCHAR NOT NULL,
  couple_fac VARCHAR NOT NULL,
  eff_date TIMESTAMP,
  rate_type VARCHAR NOT NULL,
  age_for_sorting VARCHAR NOT NULL,
--   Lowest_Rate_ VARCHAR NOT NULL,
--   Highest_Rate_ VARCHAR NOT NULL,
  age VARCHAR NOT NULL,
  policy_fee VARCHAR,
  household_discount VARCHAR,
  monthly_rate VARCHAR NOT NULL,
  quarterly_rate VARCHAR NOT NULL,
  semi_annual_rate VARCHAR NOT NULL,
  annual_rate VARCHAR NOT NULL
)
